version: '3.7'

x-shared-api-variables: &shared-api-variables
  NODE_ENV: development
  ENV_PREFIX: ONIFY_
  INTERPRET_CHAR_AS_DOT: _
  ONIFY_db_elasticsearch_host: http://linked-elasticsearch:9200
  ONIFY_db_indexPrefix: dev
  ONIFY_client_secret: ${API_CLIENT_SECRET}
  ONIFY_client_code: ${API_CLIENT_CODE}
  ONIFY_client_instance: ${API_CLIENT_INSTANCE}
  ONIFY_evaluationLicense: ${LICENSE} # Contact Onify at hello@onify.co for license
  ONIFY_adminUser_username: admin
  ONIFY_adminUser_password: ${ADMIN_PASSWORD}
  ONIFY_adminUser_email: hello@onify.co
  ONIFY_apiTokens_app_secret: ${API_APP_SECRET}
  ONIFY_logging_logLevel: info
  ONIFY_resources_baseDir: ./data/resources
  ONIFY_resources_tempDir: ./data/storage
  ONIFY_websockets_agent_url: ws://linked-agent-server:8080/hub

x-shared-api-volumes: &shared-api-volumes # make sure the paths exist
  - ./tmp/resources:/usr/app/data

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m # can be increased but make sure it doesn't exceed docker limits
      - discovery.type=single-node
      - cluster.name=onify
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5m
      retries: 30
    # volumes: # uncomment to persist elasticsearch data
    #   - ./tmp/elasticsearch:/usr/share/elasticsearch/data
  agent-server:
    image: eu.gcr.io/onify-images/hub/agent-server:2 # replace :2 with desired semver version
    environment:
      hub_version: v2
      log_level: "2"
      log_type: "2"
    ports:
      - 8080:8080
  api:
    image: eu.gcr.io/onify-images/hub/api:2 # replace :2 with desired semver version
    restart: always
    depends_on:
      - elasticsearch
    environment:
      <<: *shared-api-variables
      ONIFY_autoinstall: "true"
    ports:
      - 8181:8181
    links:
      - elasticsearch:linked-elasticsearch
      - agent-server:linked-agent-server
    volumes: *shared-api-volumes
  worker:
    image: eu.gcr.io/onify-images/hub/api:2 # replace :2 with desired semver version
    command: worker
    restart: always
    depends_on:
      - elasticsearch
    environment:
      <<: *shared-api-variables
      ONIFY_worker_cleanupInterval: "30"
    links:
      - elasticsearch:linked-elasticsearch
      - agent-server:linked-agent-server
    volumes: *shared-api-volumes
  app:
    image: eu.gcr.io/onify-images/hub/app:2
    restart: always
    depends_on:
      - api
    environment:
      ONIFY_API_TOKEN: ${APP_API_TOKEN}
      ONIFY_API_URL_INTERNAL: http://linked-api:8181/api/v2
      ONIFY_API_URL_EXTERNAL: http://localhost:8181/api/v2
    links:
      - api:linked-api
    ports:
      - 3000:3000
