apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  admin_password: <base64-encoded-string> # admin password
  app_token_secret: <base64-encoded-string> # app token secret
  client_secret: <base64-encoded-string> # client encryption key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: default
data:
  NODE_ENV: production # environment
  ENV_PREFIX: ONIFY_ #
  INTERPRET_CHAR_AS_DOT: _
  ONIFY_adminUser_username: admin
  ONIFY_autoinstall: "true"
  ONIFY_client_code: onify
  ONIFY_client_instance: evaluation
  ONIFY_db_elasticsearch_host: http://elasticsearch:9200
  ONIFY_db_indexPrefix: onify # indices will be prefixed with this string
  ONIFY_initialLicense: <onify_license> # Contact Onify at hello@onify.co for license
  ONIFY_resources_baseDir: /usr/share/onify/resources
  ONIFY_resources_tempDir: /usr/share/onify/temp_resources
  ONIFY_websockets_agent_url: ws://agent-server:8080/hub
--- # Api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: onify_regcred
      containers:
      - name: api
        image: eu.gcr.io/onify-k8s/hub-api/v2:2
        envFrom:
        - configMapRef:
            name: api-config
        env:
        - name: ONIFY_adminUser_password
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: admin_password
        - name: ONIFY_apiTokens_app_secret
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: app_token_secret
        - name: ONIFY_client_secret
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: client_secret
        volumeMounts:
        - name: resources
          mountPath: /usr/share/onify
        ports:
        - name: api
          containerPort: 8181
      volumes:
      - name: resources
        hostPath:
          path: /data/onify # host resource folder
          type: Directory
--- # Expose api as service
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - protocol: TCP
      name: api
      port: 8181
  selector:
    app: api
--- # Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
       - name: onify_regcred
      containers:
      - name: worker
        image: eu.gcr.io/onify-k8s/hub-api/v2:2
        args:
        - worker # act as worker
        envFrom:
        - configMapRef:
          name: api-config
        env:
        - name: ONIFY_worker_cleanupInterval # interval to clean up temporary files, in seconds
          value: "300"
        - name: ONIFY_adminUser_password
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: admin_password
        - name: ONIFY_apiTokens_app_secret
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: app_token_secret
        - name: ONIFY_client_secret
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: client_secret
        volumeMounts:
        - name: resources
          mountPath: /usr/share/onify
      volumes:
      - name: resources
        hostPath:
          path: /data/onify
          type: Directory

