apiVersion: v1
kind: Secret
metadata:
  name: onify-app-secrets
type: Opaque
data:
  api_token: <base64-encoded-string> # "Bearer api_token_secret_base64"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onify-app
  labels:
    app: onify
    tier: app
spec:
  selector:
    matchLabels:
      app: onify
      tier: app
  template:
    metadata:
      labels:
        app: onify
        tier: app
    spec:
      imagePullSecrets:
      - name: onify-regcred
      containers:
      - name: app
        image: eu.gcr.io/onify-images/hub/app:2
        env:
        - name: ONIFY_API_TOKEN
          valueFrom:
           secretKeyRef:
             name: onify-app-secrets
             key: api_token
        - name: ONIFY_API_URL_INTERNAL
          value: http://onify-api:8181/api/v2
        - name: ONIFY_API_URL_EXTERNAL
          value: http://localhost:8181
        ports:
        - name: app
          containerPort: 3000
---
# Expose app as service
apiVersion: v1
kind: Service
metadata:
  name: onify-app
  labels:
    app: onify
    tier: app
spec:
  selector:
    app: onify
    tier: app
  ports:
    - protocol: TCP
      name: onify-app
      port: 3000
