kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-data
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: es-data
spec:
  storageClassName: es-data
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/elasticsearch
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
spec:
  storageClassName: es-data
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.6.2
        env:
        - name: ES_JAVA_OPTS
          value: -Xms8g -Xmx8g
        - name: discovery.type # remove if replicas is above 1
          value: single-node
        - name: cluster.name
          value: onify
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: es-data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: elasticsearch
