kind: PersistentVolume
apiVersion: v1
metadata:
  name: onify-elasticsearch-pv
  labels:
    app: onify
    tier: persistance
  annotations:
    volume.alpha.kubernetes.io/storage-class: onify-elasticsearch-pv
spec:
  storageClassName: onify-elasticsearch-pv
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/Users/Shared/onify/es" # Local OSX example
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onify-elasticsearch-pvc
  labels:
    app: onify
    tier: persistance
spec:
  storageClassName: onify-elasticsearch-pv
  selector:
    matchLabels:
      app: onify
      tier: persistance
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: onify
    tier: persistance
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: onify
      tier: persistance
  template:
    metadata:
      labels:
        app: onify
        tier: persistance
        service: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.11.1
        env:
        # - name: ES_JAVA_OPTS
        #   value: -Xms1g -Xmx1g # increase jvm heap size when available RAM is known
        - name: discovery.type # remove if replicas is above 1
          value: single-node
        - name: cluster.name
          value: onify
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: onify-elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: onify
    tier: persistance
    service: elasticsearch
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: onify
    tier: persistance
    service: elasticsearch
