apiVersion: v1
kind: Secret
metadata:
  name: onify-api-secrets
type: Opaque
data:
  admin_password: <base64 admin password>
  app_token_secret: <base64 app_token_secret>
  client_secret: <base64 client secret>